on: 
    release:
        types:
          - published

name: Push to game template

jobs:
    game-template:
        name: Push new version to game template
        runs-on: ubuntu-latest
        env:
            ADDON: "egoventure"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: "release"
            - name: Checkout game template
              uses: actions/checkout@v2
              with: 
                  repository: "deep-entertainment/egoventure-game-template"
                  ref: "develop"
                  path: "game-template"
                  token: "${{ secrets.DEPLOYMENT_TOKEN }}"
                  fetch-depth: 0
            - name: "Copy ${{ env.ADDON }} version ${{ github.event.release.tag_name }}"
              run: |
                rm -rf game-template/addons/$ADDON
                cp -r release/addons/$ADDON game-template/addons
            - name: "Commit"
              uses: EndBug/add-and-commit@v7.2.1
              with:
                cwd: game-template
                message: 'feat: Adding $ADDON version ${{ github.event.release.tag_name }}'
                push: true

